package com.splitwise.dao.repository;

import static com.splitwise.constant.SpliwiseConstants.GROUP_TABLE;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.util.StringUtils;

import com.splitwise.dao.GroupDao;
import com.splitwise.dao.MySQLTemplate;
import com.splitwise.modal.Group;

@Repository
public class GroupRepository implements GroupDao {

	@Autowired
	private MySQLTemplate mySQLTemplate;

	@Override
	public Integer addGroup(Group group) {

		if (StringUtils.isEmpty(group.getIsActive())) {
			group.setIsActive(true);
		}
		return mySQLTemplate.insertAndGetAutoGeneratedKey(group, GROUP_TABLE, Group.class);
	}

	@Override
	public Group getGroup(Integer group_id) {

		Group group = new Group();
		group.setGroup_id(group_id);
		return mySQLTemplate.getRecordOnBasisOfId(group, group_id, GROUP_TABLE, Group.class);
	}

	@Override
	public List<Group> getAllGroups() {
		return mySQLTemplate.getAllRecords(GROUP_TABLE, Group.class);
	}

	@Override
	public boolean updateGroup(Group group) {
		return mySQLTemplate.updateRecord(group, GROUP_TABLE, Group.class);
	}

	@Override
	public boolean deleteGroup(Integer group_id) {

		Group group = new Group();
		group.setGroup_id(group_id);
		group.setIsActive(false);
		return mySQLTemplate.updateRecord(group, GROUP_TABLE, Group.class);
	}

}
