package com.splitwise.modal.common;

public interface Persistable {

	public String getPrimaryKeyField();

	public boolean isAutoGeneratedField();

	public Integer getGroup_id();

	public void setGroup_id(Integer group_id);
}
