package com.splitwise.modal;

import com.splitwise.modal.common.Persistable;

public class Country implements Persistable {

	private String country_name;
	private String country_currency;
	private String currency_symbol;

	public String getCountry_name() {
		return country_name;
	}

	public void setCountry_name(String country_name) {
		this.country_name = country_name;
	}

	public String getCountry_currency() {
		return country_currency;
	}

	public void setCountry_currency(String country_currency) {
		this.country_currency = country_currency;
	}

	public String getCurrency_symbol() {
		return currency_symbol;
	}

	public void setCurrency_symbol(String currency_symbol) {
		this.currency_symbol = currency_symbol;
	}

	@Override
	public String getPrimaryKeyField() {
		return "country_name";
	}

	@Override
	public boolean isAutoGeneratedField() {
		return false;
	}

	@Override
	public Integer getGroup_id() {
		return null;
	}

	@Override
	public void setGroup_id(Integer group_id) {
	}

}
