package com.splitwise.modal;

import com.splitwise.modal.common.Persistable;

public class Group implements Persistable {

	private Integer group_id;
	private Integer members_count;
	private String created_date;
	private Boolean isActive;
	private Double total_group_spent;

	@Override
	public String getPrimaryKeyField() {
		return "group_id";
	}

	@Override
	public boolean isAutoGeneratedField() {
		return true;
	}

	@Override
	public Integer getGroup_id() {
		return group_id;
	}

	@Override
	public void setGroup_id(Integer group_id) {
		this.group_id = group_id;
	}

	public Integer getMembers_count() {
		return members_count;
	}

	public void setMembers_count(Integer members_count) {
		this.members_count = members_count;
	}

	public String getCreated_date() {
		return created_date;
	}

	public void setCreated_date(String created_date) {
		this.created_date = created_date;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Double getTotal_group_spent() {
		return total_group_spent;
	}

	public void setTotal_group_spent(Double total_group_spent) {
		this.total_group_spent = total_group_spent;
	}

}
