package com.splitwise.modal;

import com.splitwise.modal.common.Persistable;

public class Login implements Persistable {

	private int id;
	private String email;
	private String password;
	private boolean isActive;

	public Login(String email, String password, boolean isActive) {
		super();
		this.email = email;
		this.password = password;
		this.isActive = isActive;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isActive() {
		return isActive;
	}

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Override
	public String getPrimaryKeyField() {
		return "id";
	}

	@Override
	public boolean isAutoGeneratedField() {
		return true;
	}

	@Override
	public Integer getGroup_id() {
		return null;
	}

	@Override
	public void setGroup_id(Integer group_id) {
	}

}
