package com.splitwise.modal;

import com.splitwise.modal.common.Persistable;

public class Owes implements Persistable {

	private Integer owes_ID;
	private Integer group_id;
	private Integer transaction_id;
	private String owes_by_user;
	private String owes_to_user;
	private Double amount;

	public Owes() {
		super();
	}

	public Owes(Integer group_id, Integer transaction_id, String owes_by_user, String owes_to_user, Double amount) {
		super();
		this.group_id = group_id;
		this.transaction_id = transaction_id;
		this.owes_by_user = owes_by_user;
		this.owes_to_user = owes_to_user;
		this.amount = amount;
	}

	public Owes(Integer group_id) {
		super();
		this.group_id = group_id;
	}

	@Override
	public String getPrimaryKeyField() {
		return "owes_ID";
	}

	@Override
	public boolean isAutoGeneratedField() {
		return true;
	}

	@Override
	public Integer getGroup_id() {
		return group_id;
	}

	@Override
	public void setGroup_id(Integer group_id) {
		this.group_id = group_id;
	}

	public Integer getOwes_ID() {
		return owes_ID;
	}

	public void setOwes_ID(Integer owes_ID) {
		this.owes_ID = owes_ID;
	}

	public Integer getTransaction_id() {
		return transaction_id;
	}

	public void setTransaction_id(Integer transaction_id) {
		this.transaction_id = transaction_id;
	}

	public String getOwes_by_user() {
		return owes_by_user;
	}

	public void setOwes_by_user(String owes_by_user) {
		this.owes_by_user = owes_by_user;
	}

	public String getOwes_to_user() {
		return owes_to_user;
	}

	public void setOwes_to_user(String owes_to_user) {
		this.owes_to_user = owes_to_user;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}
}
