package com.splitwise.modal;

import com.splitwise.modal.common.Persistable;

public class User implements Persistable {

	private String email_id;
	private String name;
	private String mobile;
	private String date_of_birth;
	private String country;
	private Integer group_id;
	private Double total_owes;
	private String comment;
	private Boolean isActive;

	@Override
	public String getPrimaryKeyField() {
		return "email_id";
	}

	@Override
	public boolean isAutoGeneratedField() {
		return false;
	}

	public String getEmail_id() {
		return email_id;
	}

	public void setEmail_id(String email_id) {
		this.email_id = email_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getDate_of_birth() {
		return date_of_birth;
	}

	public void setDate_of_birth(String date_of_birth) {
		this.date_of_birth = date_of_birth;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Override
	public Integer getGroup_id() {
		return this.group_id;
	}

	@Override
	public void setGroup_id(Integer group_id) {
		this.group_id = group_id;
	}

	public Double getTotal_owes() {
		return total_owes;
	}

	public void setTotal_owes(Double total_owes) {
		this.total_owes = total_owes;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Boolean isActive() {
		return isActive;
	}

	public void setActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
